### ISSUE TITLE
Support for moving columns

### ISSUE THREAD

**Issue by tomaj** [lulco/phoenix#1]
It will be useful if you can specify where you would like to put new column (after some other, or before). 

Also special method for moving columns?

**Comment by lulco** [comment]
This is supported only in MySql. Pgsql and SQLite don't support this behavior.

**Comment by tomaj** [comment]
It is possible even in postgre, but it is little bit tricky :-) https://wiki.postgresql.org/wiki/Alter_column_position

**Comment by lulco** [comment]
Well yes, it is posibble, but you have to read "information schema" and move all data. I am trying to write this library without doing this. But maybe once I will have to change everything and start to use schema tables.
