### ISSUE TITLE
Support for raw SQL

### ISSUE THREAD

**Issue by CWSpear** [lulco/phoenix#147]
Maybe it's there, but I couldn't find it in the docs, nor after digging through the code a big.

Would it be possible to support raw SQL?

```php
function up() : void
{
  $this->executeRawSQL('--do something nonstandard');
}

function down(): void
{
  $this->executeRawSQL('--manually undo what we did in up()');
}
```

**Comment by CWSpear** [comment]
Would be cool if it could support SQL files, too. `$this->executeFile('filename.sql');`

**Comment by lulco** [comment]
Hello,
you can try:

```php
function up() : void
{
    $this->execute('--do something nonstandard');
}
```
or
```php
function up() : void
{
    $this->execute(file_get_contents('filename.sql'));
}
```

Please, let me know, if it worked

**Comment by CWSpear** [comment]
Ah, thanks! That should work. Sorry, I knew I might have just been missing it.
