### ISSUE TITLE
PORT for connections

### ISSUE THREAD

**Issue by KarelWintersky** [lulco/phoenix#154]
`port` option for db connection environment sections required

Why?

For example, I use this configuration for access to DB inside docker container:

```
'docker57' => [
        'adapter'   => 'mysql',
        'hostname'  =>  '0.0.0.0',
        'username'  =>  'user',
        'password'  =>  'password',
        'database'  =>  'database',
        'charset'   =>  'utf8',
        'port'      =>  6603
    ],
```

**Comment by lulco** [comment]
Hello, what do you mean "port is required". If you look to: https://github.com/lulco/phoenix/blob/master/src/Config/EnvironmentConfig.php#L30 you can see that port is optional.

Or how do you would like to configure that?

**Comment by KarelWintersky** [comment]
pls, add commented line to configuration file as EXAMPLE

**Comment by lulco** [comment]
Sorry, I misunderstood your first message. I added info about port to config examples, readme and docs
