### ISSUE TITLE
CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by dmoreno1828** [lulco/phoenix#160]
I added in the line 176, in file **MysqlQueryBuilder**,  the following sentence to accept   **CURRENT_TIMESTAMP**
            if ($column->getSettings()->getDefault() == 'CURRENT_TIMESTAMP') {
                return $default .= $column->getSettings()->getDefault();
            }

**Comment by lulco** [comment]
Hi @dmoreno1828 thank you for your message. Can you prepare Pull request with this change and add this behavior also to pgsql query builder?

**Comment by dmoreno1828** [comment]
Yes, I'm going to try it with pgsql query builder.

**Comment by lulco** [comment]
Closed by #161
