### ISSUE TITLE
Implement recommended way of UNIQUE CONSTRAINT (possible BC)

### ISSUE THREAD

**Issue by lulco** [lulco/phoenix#171]
see fork: https://github.com/aksafan/phoenix/commit/791387f1df287f66cd1d5bb90e68cf0de12cb8c3

and documentation:
https://www.postgresql.org/docs/9.4/indexes-unique.html

**Comment by lulco** [comment]
Check table pg_index - column unique - before this change. How will this implementation work?

**Comment by lulco** [comment]
for us everything works, we will not change it

**Comment by aksafan** [comment]
Hey @lulco,

I've added unique constrains support [here](https://github.com/lulco/phoenix/pull/289).
Please review.
