### ISSUE TITLE
Type "year" is not allowed - valid MySQL column type

### ISSUE THREAD

**Issue by JohnWE** [lulco/phoenix#237]
Run `vendor/bin/phoenix dump` on a database with a MySQL table with a `Year` column.

More about the Year column type: https://dev.mysql.com/doc/refman/5.7/en/year.html

Can someone add a TYPE_YEAR?  I'm not familiar enough with this library to know where else might need to use it other than Column.php.

**Comment by lulco** [comment]
Hi @JohnWE 
Thanks for report!
I'll check it and try to add. As I remember, pgsql doesn't support year column type, but if we need it in mysql, I probably add some fallback to integer or so.

**Comment by JohnWE** [comment]
It's not very often used, and an integer fallback would probably be fine.

**Comment by lulco** [comment]
Can you check this branch https://github.com/lulco/phoenix/pull/238? or require lulco/phoenix:dev-year-column-type in composer.

I have to add some additional tests, but it should work.

**Comment by lulco** [comment]
Merged to master, so try lulco/phoenix:dev-master and let me know if everything works or there are some problems. Thanks.

**Comment by JohnWE** [comment]
Works, thanks for the quick turnaround!

**Comment by lulco** [comment]
OK, at the end of may there is planned next release 1.8.0
