### ISSUE TITLE
Single quote in comment breaks sql

### ISSUE THREAD

**Issue by JohnWE** [lulco/phoenix#240]
When I have a column like this:

```
$this->table('test', 'col_name')
            ->addColumn('col_name', 'integer', ['comment' => 'Row ID\'s favorite comment'])
            ->create();
```

In MySQL, I get an error creating the table.  It's because of the comment.

**Comment by lulco** [comment]
Hi thanks for reporting, can you provide failing test case?
For example here https://github.com/lulco/phoenix/blob/master/testing_migrations/phoenix/20150529123120_init.php

**Comment by JohnWE** [comment]
https://gist.github.com/JohnWE/d6134dccd0bf23a9c7db62165f336d11

**Comment by JohnWE** [comment]
Thanks for fixing!
