### ISSUE TITLE
Dump MySQL Tinyint column changes

### ISSUE THREAD

**Issue by JohnWE** [lulco/phoenix#243]
I encountered two issues where dump didn't properly convert a Tinyint(1) column.

1. A column with a default that's not 0 or 1.  In MySQL, Tinyint columns can range from -127 to 128 or 0 to 255 if unsigned.  A column like this:

`num_endorsements_to_publish TINYINT(1) UNSIGNED NOT NULL DEFAULT 3,`

gets dumped as:

`->addColumn('num_endorsements_to_publish', 'boolean', ['default' => true, 'signed' => false])`

missing the proper default value.

2. A column with a null default:

`approved TINYINT(1) UNSIGNED DEFAULT NULL COMMENT 'Whether this request was approved or rejected or not touched yet',`

gets dumped as: 

`->addColumn('approved', 'boolean', ['null' => true, 'default' => false, 'signed' => false, 'comment' => 'Whether this request was approved or rejected or not touched yet'])`

where the default should be null.

Maybe those would be fixed by the same code change?  I appreciate dump checking for a boolean column, but maybe it could exempt the times when the default is not 0 or 1 and keep it as a `tinyinteger` type?

**Comment by lulco** [comment]
Hi thank you again for reporting :)

tinyint(1) was picked as closest type for boolean in mysql because it has no boolean type. So it is mapped to boolean in dump command.

But as you said we probably could check the default value and maybe also if it is nullable, and if so, keep type as tinyint(1). I need to analyse code deeper and let you know.

**Comment by lulco** [comment]
@JohnWE can you try this branch? https://github.com/lulco/phoenix/pull/245

**Comment by lulco** [comment]
maybe we should remove signed setting for boolean columns

**Comment by JohnWE** [comment]
Works great, thanks!
