### ISSUE TITLE
Will seed filling function like Phoenix be supported in the future

### ISSUE THREAD

**Issue by ghost** [lulco/phoenix#249]

**Comment by lulco** [comment]
In Phoenix, seeders can be also part of migrations. You can just use `insert` method:

```
$this->insert('tableName', [data]);
```

You can insert one row per insert:
```
    $this->insert('my_table', [
        'id' => 1,
        'title' => 'Title 1',
    ]);
```
or multiple rows:
```
    $this->insert('my_table', [
        [
            'id' => 2,
            'title' => 'Title 2',
        ],
        [
            'id' => 3,
            'title' => 'Title 3',
        ],
    ]);
```

There are also `update`, `delete`, `fetch` and `fetchAll` methods for manipulating with data.

**Comment by ghost** [comment]
Thank you very much. I like Phoenix's simplicity and easy integration, and I hope it can keep it alive

**Comment by lulco** [comment]
thanks for kind words :)
