### ISSUE TITLE
How to do fresh migrate?

### ISSUE THREAD

**Issue by iRaziul** [lulco/phoenix#258]
In laravel we can use `migrate:fresh` to clear the database and migrate everything.
How can I do it in phoenix?

**Comment by lulco** [comment]
In case you used Phoenix to create your database, you can run cleanup command. It will rollback all your migrations and at the end you should have empty db.

To cleanup database structure which was not created by Phoenix you have to use some external tool like command line or adminer or php my admin etc.

Or send PR with new command :)

**Comment by iRaziul** [comment]
Thanks :)
