### ISSUE TITLE
Added support symfony >= 6

### ISSUE THREAD

**Issue by MarcHagen** [lulco/phoenix#273]
`"symfony/yaml": "^3.1|^4.0|^5.0",` > `"symfony/yaml": "^3.4|^4.0|^5.0|^6.0"`

Maybe some testing is needed?

**Comment by lulco** [comment]
I tried it before, it didn’t work because of some BC breaks in version 6. I don’t remember the problem :D have to try it again.

**Comment by MarcHagen** [comment]
Ah, well sometimes is maybe good, sometimes is maybe shit

**Comment by MarcHagen** [comment]
After some testing and digging its because Symfony 6 is really using the PHP 8+ type hints .
Which are not BC with older PHP, 

Example:
breaking `AbstractCommand` class on function `setName`.
6.0+ Symfony/Command requires `public function setName(string $name): static` 
Error:
```
Fatal error: Declaration of Phoenix\Command\AbstractCommand::setName($name) must be compatible with Symfony\Component\Console\Command\Command::setName(string $name): static in /home/runner/work/phoenix/phoenix/src/Command/AbstractCommand.php on line 49
```

So to support Symphony 6 it seems that there need to be a mandantory PHP 8+ for the package. 
Which is good and bad, seeing PHP 7.4 is going EOL end this year, but can understand the compatibility back to ~7.x or not wanting to maintain multiple versions.

**Comment by lulco** [comment]
Well, I personally and also my company using php 7.4 for now. So I can't and also don't want to drop support for it in phoenix. I'll check this again, maybe I can do some "minor breaking change" in version 2.0.0 which I am already preparing

**Comment by lulco** [comment]
It seems I've fixed it please check https://github.com/lulco/phoenix/pull/274 or dev-symfony-6 in composer. 

Note: One test is failing, but it is because of that testing library doesn't support symfony 6 yet. I'll handle it in few days.

**Comment by MarcHagen** [comment]
That is awesome! Thank you for putting some time into this, really much appreciated

**Comment by lulco** [comment]
Merged to master, I'll test it for a while and then I'll release v 2.0.0

**Comment by MarcHagen** [comment]
```bash
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 3 updates, 1 removal
  - Removing symfony/polyfill-php73 (v1.24.0)
  - Upgrading lulco/phoenix (1.11.1 => dev-master ea84789)
  - Upgrading symfony/console (v5.4.2 => v6.0.2)
  - Upgrading symfony/finder (v5.4.2 => v6.0.2)
Writing lock file
```

I'm already happy :) again thank you !

**Comment by lulco** [comment]
please, if you'll find any issue, report it and I will try to fix it :)
