### ISSUE TITLE
ROW_FORMAT

### ISSUE THREAD

**Issue by darkalchemy** [lulco/phoenix#275]
Hello,

Would you be able to implement ROW_FORMAT?

I know that I can include it when using raw sql, but it would be nice to have this in the created dumps, etc.

Thank you

**Comment by lulco** [comment]
Hi, can you elaborate? Where do you want to use ROW_FORMAT? 
For dumps in raw format the best command is native mysqldump (or psql alternative)

**Comment by darkalchemy** [comment]
Hi @lulco,

So when I create a migration, I would like to include the engine and row_format, just as if I used raw sql. Or, if not part of the schema, maybe as a configurable item in the config file?

```
CREATE TABLE `first_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `url` varchar(255) NOT NULL,
  `sorting` int(11) NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_first_table_url` (`url`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPRESSED;
```
```
$this->table('first_table,['row_format', 'compressed']')
    ->addColumn('title', 'string')
    ->addColumn('url', 'string')
    ->addColumn('sorting', 'integer')
    ->addColumn('created_at', 'datetime')
    ->addIndex('url', Index::TYPE_UNIQUE)
    ->create();
}
```
Thanks

**Comment by lulco** [comment]
I see. Ok I'll check those options if they are common for both - mysql and psql.

**Comment by darkalchemy** [comment]
It looks like MariaDB has deprecated InnoDB compressed tables in 10.6.

I will close this as no longer needed.

Thanks @lulco
