### ISSUE TITLE
Is there a way to specify default template?

### ISSUE THREAD

**Issue by MekDrop** [lulco/phoenix#276]
I would like to set default migration template, so I wouldn't need to specify everytime when I run create command. Is there a way how to do that?

**Comment by lulco** [comment]
Hi @MekDrop,
there is not such option for now, but I can imagine it could be in config file like `log_table_name` is. Also, with template we need to setup indent (and maybe some other options).

**Comment by lulco** [comment]
@MekDrop it is ready for test, use `dev-template-and-indent-in-config` branch in you composer.json
