### ISSUE TITLE
Using phoenix.yml file causes `Class Symfony\...\Yaml doesn't exist. Run composer require symfony/yaml`

### ISSUE THREAD

**Issue by rvrbk** [lulco/phoenix#277]
If I want to use a .yml file for configuration I get  `Class Symfony\...\Yaml doesn't exist. Run composer require symfony/yaml`.

I've seen it's in the `suggests` section in `composer.json` but is't that section meant for packages that improve behaviour rather than 'optional' ones?

I've found no way to install this and the code breaks, I want to suggest putting this in the `require` section.

**Comment by lulco** [comment]
Did you run composer require symfony/yaml in your application as it is suggested? Did it print some error(s)?

symfony/yaml is not required for Phoenix so we will not put it to require section. But it is tested so it should work

**Comment by rvrbk** [comment]
Hi, thanks for responding. I understand it will work once I install that dependency, I was just wondering if it isn't better practice to put it in the `require` section since the code breaks first if you're trying to use it, I expected it to run, no matter the format of the configuration file. It's just a difference of opinion.

**Comment by lulco** [comment]
I believe that the way how it is implemented is the best practice.

Your suggestion would install symfony/yaml, nette/neon and require ext-json for all Phoenix users, even for those using php config.

**Comment by rvrbk** [comment]
That's true, the package would become more bloated

**Comment by lulco** [comment]
closing as answered
