### ISSUE TITLE
Run migrations without command line

### ISSUE THREAD

**Issue by ryanstubbs** [lulco/phoenix#285]
I was just wondering if it were possible to run migrations without access to the command line? It's quite useful for deploying to shared hosting accounts or places where command line access is limited.

Thanks :)

**Comment by lulco** [comment]
Hi, no this is not possible. As I know, phinx had this option

**Comment by lulco** [comment]
I just tried to run StatusCommand from web interface, and it works. You will need some Input / Output implementations e.g. to use some GET parameter or so, but it should work.

Here is code skeleton:
```

if (isset($_GET['phoenix'])) {
    $input = new class implements InputInterface
    {
        // TODO implement input interface
    };

    $output = new class implements OutputInterface
    {
        // TODO implement output interface
    };

    if ($_GET['phoenix'] === 'status') {
        $command = new StatusCommand();
    } else {
        // TODO other commands
    }

    $configuration = []; // TODO load configuration
    $command->setConfig($configuration);
    exit($command->execute($input, $output));
}
```
