### ISSUE TITLE
Diff command with MariaDB (null as default value)

### ISSUE THREAD

**Issue by odan** [lulco/phoenix#287]
Hi!

Usually I use MySQL, but this time I have a MariaDB server. 
In MariaDB the schema field `COLUMN_DEFAULT` contains 'NULL' as string to define null as default.
So when I create a schema diff, the generated PHP code like this:

Actual output:

```php
$this->table('table_name')
    ->addColumn(
        'field_name', 'string',
        [
            'null' => true,
            'default' => 'NULL', // <- should be null
            'length' => 36,
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
        ]
    )
    ->save();
```

Expected output:

```php
$this->table('table_name')
    ->addColumn(
        'field_name', 'string',
        [
            'null' => true,
            'default' => null,
            'length' => 36,
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
        ]
    )
    ->save();
```

Is there an option, to change this mapping?

**Comment by lulco** [comment]
Interesting, it is new for me. `From [MariaDB 10.2.7](https://mariadb.com/kb/en/mariadb-1027-release-notes/), literals are quoted to distinguish them from expressions. NULL means that the column has no default.` 

We already have mechanism for json feature in mysql so it would be possible check this version of mariadb, too.

I don’t use mariadb but if you prepare PR with tests on old (10.2.6) and new (10.2.7) version of mariadb, I will merge it. Maybe tests are ready, we would just need new action in github workflows
